# Conditional Statements

In [1]:
z = 4
if z % 2 == 0 : 	# True
	print("z is even")	# É par
	print("other text")
elif z == 3 :
	pint("z equal 3")	# Igual a 3
else :
	print("z is odd")	# É ímpar

z is even
other text


# Loop statements

* While
* For
  * Classic
  * Dictionaries
  * Numpy arrays
  * Pandas DataFrames

In [4]:
# While loop
error = 50.0
while error > 1:
	error = error / 4
	print(error)

12.5
3.125
0.78125


In [5]:
# For loop
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam:
	print(height)
for index, height in enumerate(fam):
	print("person " + str(index) + ": " + str(height))

1.73
1.68
1.71
1.89
person 0: 1.73
person 1: 1.68
person 2: 1.71
person 3: 1.89


In [8]:
# For for dictionaries
world_dict = {"afghanistan":30.55, "albania":2.77, "algeria":39.21}
for key, value in world_dict.items():
	print(key + " -- " + str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21


In [29]:
# For for Numpy Arrays
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89])
np_weight = np.array([65,4, 59.2, 63.5, 88.4])
meas = np.array([np_height, np_weight])
for val in meas:
	print(val)	# Faz duas impressões, cada uma de um array inteiro
for val in np.nditer(meas, flags=["refs_ok"]):
	print(val)	# Faz oito impressões, primeiro das alturas e depois dos pesos

[1.73 1.68 1.71 1.89]
[65.   4.  59.2 63.5 88.4]
[1.73 1.68 1.71 1.89]
[65.   4.  59.2 63.5 88.4]


In [ ]:
# For for Pandas DataFrame
import pandas as pd

brics = pd.read_csv("path/to/brics.csv", index_col = 0)
for val in brics:
	print(val)	# Imprime apenas os títulos das colunas

for label, row in brics.iterrows():
	print(label)	# Imprime o label do DataFrame
	print(row)		# Imprime todo os restante dos dados do registro

for label, row in brics.iterrows():
	print(label + ": " + row["capital"]) # Imprime o "label" e mais a capital